# Generated by Django 4.0.3 on 2022-03-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_response_remove_question_question_type_delete_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question_type',
            new_name='response_type',
        ),
    ]
